name: WallsOfBetrayal
main: fenomeno\WallsOfBetrayal\Main
api: 5.0.0
version: 1.0.0
author: fenomeno

permissions:
  command.choose:
    default: true
  command.kit:
    default: true
  command.abilities:
    default: true
  command.shop:
    default: true
  wob.kit.sentinel:
    default: op