name: WallsOfBetrayal
main: fenomeno\WallsOfBetrayal\Main
api: 5.0.0
version: 1.0.0
author: fenomeno

permissions:
  wob.command.choose:
    default: true
  wob.command.kit:
    default: true
  wob.command.abilities:
    default: true
  wob.command.shop:
    default: true
  wob.kit.sentinel:
    default: op
  wob.command.balance:
    default: true
  wob.command.pay:
    default: true
  wob.command.rich:
    default: true
  wob.command.addbalance:
    default: op
  wob.command.removebalance:
    default: op
  wob.command.setbalance:
    default: op