name: WallsOfBetrayal
main: fenomeno\WallsOfBetrayal\Main
api: 5.0.0
version: 1.0.0
author: fenomeno

permissions:
  wob.command.choose:
    default: true
  wob.command.kit:
    default: true
  wob.command.abilities:
    default: true
  wob.command.shop:
    default: true
  wob.kit.sentinel:
    default: op
  wob.command.balance:
    default: true
  wob.command.pay:
    default: true
  wob.command.rich:
    default: true
  wob.command.addbalance:
    default: op
  wob.command.removebalance:
    default: op
  wob.command.setbalance:
    default: op
  wob.command.feed:
    default: op
  wob.kit.warlord:
    default: op
  wob.command.setrole:
    default: op
  wob.command.addpermission:
    default: op
  wob.command.removepermission:
    default: op
  wob.command.role:
    default: true
  wob.command.addsubrole:
    default: op
  wob.command.removesubrole:
    default: op
  wob.command.createrole:
    default: op
  wob.command.listroles:
    default: op
  wob.command.vault:
    default: true
  wob.command.vault.1:
    default: true
  wob.command.vault.2:
    default: op
  wob.command.vault.3:
    default: op
  wob.command.vault.4:
    default: op
  wob.command.vault.5:
    default: op
  wob.command.vault.other:
    default: op
  wob.abilities.builder_grace:
    default: true
  wob.command.givekit:
    default: op
  wob.command.spawner:
    default: op
  wob.command.sell:
    default: op
  wob.command.stats:
    default: true
  wob.command.craft:
    default: op
  wob.command.craft.other:
    default: op
  wob.command.nick:
    default: op
  wob.command.nick.reset:
    default: op
  wob.command.nick.log:
    default: op
  wob.command.mute:
    default: op
  wob.command.unmute:
    default: op
  wob.command.mutelist:
    default: op
  wob.command.ban:
    default: op
  wob.command.unban:
    default: op
  wob.command.tban:
    default: op
  wob.command.banlist:
    default: op
  wob.command.report:
    default: true
  wob.reports.see:
    default: op
  wob.command.reports:
    default: op
  wob.command.kick:
    default: op
  wob.command.staffchat:
    default: op
  wob.command.staffmod:
    default: op
  wob.command.vanish:
    default: op
  wob.command.freeze:
    default: op
  wob.command.history:
    default: op
  wob.command.randomtp:
    default: op
  wob.command.invsee:
    default: op
  wob.command.npc:
    default: op
  wob.command.npc.remove:
    default: op
  wob.command.npc.edit:
    default: op
  wob.command.npc.create:
    default: op
  wob.command.npc.list:
    default: op
  wob.command.npc.move:
    default: op
  wob.command.npc.tp:
    default: op
  wob.command.floatingtext:
    default: op
  wob.command.floatingtext.create:
    default: op
  wob.command.floatingtext.delete:
    default: op
  wob.command.floatingtext.list:
    default: op
  wob.command.floatingtext.edit:
    default: op