<?php

namespace fenomeno\WallsOfBetrayal\Commands;

final class CommandsIds
{

    public const RICH = 'rich';
    public const ABILITIES = 'abilities';
    public const CHOOSE = 'choose';
    public const KIT = 'kit';
    public const SHOP = 'shop';
    public const BALANCE = 'balance';
    public const PAY = 'pay';
    public const ADD_BALANCE = 'add-balance';
    public const REMOVE_BALANCE = 'remove-balance';
    public const SET_BALANCE = 'set-balance';
    public const FEED = 'feed';
    public const SET_ROLE = 'set-role';
    public const ADD_PERMISSION = 'add-permission';
    public const REMOVE_PERMISSION = 'remove-permission';
    public const PLAYER_ROLE_INFO = 'player-role-info';
    public const ADD_SUB_ROLE = 'add-sub-role';
    public const REMOVE_SUB_ROLE = 'remove-sub-role';
    public const CREATE_ROLE = 'create-role';
    public const LIST_ROLES = 'list-roles';
    public const VAULT = 'vault';
    public const GIVE_KIT = 'give-kit';
    public const SPAWNER = 'spawner';
    public const SELL = 'sell';
    public const STATS = 'stats';
    public const CRAFT = 'craft';
    public const NICK = 'nick';
    public const NICK_RESET = 'nick-reset';
    public const NICK_LOG = 'nick-log';
    public const MUTE = 'mute';
    public const UNMUTE = 'unmute';
    public const MUTE_LIST = 'mute-list';
    public const BAN = 'ban';
    public const UNBAN = 'unban';
    public const TEMP_BAN = 'temp-ban';
    public const BAN_LIST = 'ban-list';
    public const REPORT = 'report';
    public const REPORTS = 'reports';
    public const KICK = 'kick';
    public const STAFF_CHAT = 'staffchat';
    public const STAFF_MOD = 'staffmod';
    public const VANISH = 'vanish';
    public const FREEZE = 'freeze';
    public const HISTORY = 'history';
    public const RANDOM_TP = 'randomtp';
    public const INVSEE = 'invsee';
    public const NPC = 'npc';
    public const NPC_REMOVE = 'npc-remove';
    public const NPC_EDIT = 'npc-edit';
    public const NPC_CREATE = 'npc-create';
    public const NPC_LIST = 'npc-list';
    public const NPC_MOVE = 'npc-move';
    public const NPC_TP = 'npc-tp';
    public const FLOATING_TEXT = 'floating-text';
    public const FLOATING_TEXT_CREATE = 'floating-text-create';
    public const FLOATING_TEXT_DELETE = 'floating-text-delete';
    public const FLOATING_TEXT_EDIT = 'floating-text-edit';
    public const FLOATING_TEXT_LIST = 'floating-text-list';
    public const NPC_LOAD = 'npc-load';
    public const NPC_CLEANUP = 'npc-cleanup';
    public const LOBBY = 'lobby';
    public const SET_LOBBY = 'set-lobby';
    public const SPAWN = 'spawn';
    public const KINGDOM = 'kingdom';
    public const SET_SPAWN = 'set-spawn';
    public const KINGDOM_SPAWN = 'kingdom-spawn';
    public const KINGDOM_SET_SPAWN = 'kingdom-set-spawn';
    public const PORTAL = 'portal';
    public const SET_LOBBY_SETTING = 'set-lobby-setting';
    public const KINGDOM_INFO = 'kingdom-info';
    public const KINGDOM_TOP = 'kingdom-top';
    public const KINGDOM_MAP = 'kingdom-map';
    public const KINGDOM_CONTRIBUTE = 'kingdom-contribute';
    public const KINGDOM_ABILITIES = 'kingdom-abilities';
    public const KINGDOM_ADD_XP = 'kingdom-addxp';
    public const KINGDOM_SET_BORDERS = 'kingdom-setborder';
    public const KINGDOM_MANAGE = 'kingdom-manage';
    public const KINGDOM_KICK = 'kingdom-kick';
    public const KINGDOM_BAN = 'kingdom-ban';
    public const KINGDOM_VOTE = 'kingdom-vote';
    public const KINGDOM_TRUCE = 'kingdom-truce';
    public const KINGDOM_WAR = 'kingdom-war';
    public const KINGDOM_PEACE = 'kingdom-peace';
    public const KINGDOM_UPGRADE = 'kingdom-upgrade';
    public const KINGDOM_SHIELD = 'kingdom-shield';
    public const KINGDOM_ALARM = 'kingdom-alarm';
    public const KINGDOM_RALLY = 'kingdom-rally';
    public const KINGDOM_BOUNTY = 'kingdom-bounty';

}