database:
  type: mysql

  sqlite:
    file: qoia_wob.sqlite
  mysql:
    host: gamesnj44.bisecthosting.com
    port: 3306
    username: u567075_tVBWvXQeRe
    password: "sQnTHaXucsbZ4OnjLXfp9yWI"
    schema: s567075_qoia
  worker-limit: 1

kit_requirements_flush_interval: 5
day_length: 10
total_days: 14
phase_lengths:
  lobby: 1           # jour 0 → Lobby
  preparation: 1     # jour 1
  grind: 12          # jours 2–13
  battle: 1          # jour 14
  end: 1             # jour 15 (résultats)
cooldowns:
  cleanup_interval_seconds: 300