database:
  type: mysql

  sqlite:
    file: qoia_wob.sqlite
  mysql:
    host: dd
    port: 3
    username: a
    password: b
    schema: c
  worker-limit: 2

kit_requirements_flush_interval: 5
day_length: 10
total_days: 14
phase_lengths:
  lobby: 1           # jour 0 → Lobby
  preparation: 1     # jour 1
  grind: 12          # jours 2–13
  battle: 1          # jour 14
  end: 1             # jour 15 (résultats)

cooldowns:
  cleanup_interval_seconds: 300

vault:
  size: 27
  max_vault_number: 5

webhook:
  global:
    user-agent: "Discord Webhook Client (+PocketMine)"
    timeouts:
      connect-ms: 400
      request-ms: 2000
    ssl:
      verify-peer: true
      verify-host: true
    queue:
      max-size: 2048
    workers:
      threads: 1
    logging:
      level: "INFO"
      log-ratelimits: true
      log-payload-errors: true

  templates:
    default:
      content: "{MESSAGE}"
      username: "WallsOfBetrayal"
      avatar_url: ""
      allowed_mentions:
        parse: [ ]
        users: [ ]
        roles: [ ]
        replied_user: false
      embeds: [ ]
    error:
      content: "❌ {TITLE}\n```{DETAILS}```"
      username: "WOB • Errors"
      allowed_mentions:
        parse: [ ]